FANTOMES_VERSION = 1.0
FANTOMES_SITE = $(TOPDIR)/package/fantomes
FANTOMES_SITE_METHOD = local
FANTOMES_LICENSE = GPLv3+

FANTOMES_DEPENDENCIES = linux

define FANTOMES_BUILD_CMDS
$(MAKE) -C $(LINUX_DIR) $(LINUX_MAKE_FLAGS) M=$(@D)
endef

define FANTOMES_INSTALL_TARGET_CMDS
$(MAKE) -C $(LINUX_DIR) $(LINUX_MAKE_FLAGS) M=$(@D) modules_install
endef

$(eval $(generic-package))
